---
output:
  md_document:
    variant: gfm
---

```{r setup, message = FALSE}
set.seed(12345)
library(tidyverse)
library(deleuze)
library(patchwork)
library(Tjazi)
library(vegan)


```

```{r prepare precision assessment, fig.width = 5, fig.height = 5, cache=TRUE}

set.seed(12345)
b1 <- c(rep(1, 10), rep(5, 20), rep(15, 20), rep(40, 20), rep(80, 20), rep(100, 5), rep(250, 5) )
b2 <- c(rep(1, 30), rep(5, 15), rep(15, 15), rep(40, 15), rep(80, 15), rep(100, 5), rep(350, 5) )
b3 <- c(rep(1, 50), rep(5, 10), rep(15, 10), rep(40, 10), rep(80, 10), rep(100, 5), rep(450, 5) )


res_b1 = sapply(X = rep(seq(1000,20000, by = 1000), each = 100),FUN = function(x){
  table(factor(sample(paste0("feature_",1:100), 
                      prob = b1, 
                      replace = T, size = x), levels = paste0("feature_",1:100)))
  
})

res_b2 = sapply(X = rep(seq(1000,20000, by = 1000), each = 100),FUN = function(x){
  table(factor(sample(paste0("feature_",1:100), 
                      prob = b2, 
                      replace = T, size = x), levels = paste0("feature_",1:100)))
  
})

res_b3 = sapply(X = rep(seq(1000,20000, by = 1000), each = 100),FUN = function(x){
  table(factor(sample(paste0("feature_",1:100), 
                      prob = b3, 
                      replace = T, size = x), levels = paste0("feature_",1:100)))
  
})

```

```{r prep CLR transforms, fig.width = 8, fig.height = 15, cache=TRUE}
clr_logunif_b1_base <- res_b1 %>%
  data.frame() %>%
  Tjazi::clr_logunif() %>%
  data.frame() 

clr_const_b1_base <- res_b1 %>%  
  data.frame() %>%
  Tjazi::clr_c() %>% 
  data.frame() 
  
clr_unif_b1_base <- res_b1 %>%
  data.frame() %>%
  Tjazi::clr_unif() %>%
  data.frame()

clr_shrunk_b1_base <- res_b1 %>%
  data.frame() %>%
  sCLR() %>% 
  data.frame() 

clr_new_b1_base <- res_b1 %>% 
  data.frame() %>%
  getTableMeans() %>% 
  data.frame() 

clr_logunif_b2_base <- res_b2 %>%
  data.frame() %>%
  Tjazi::clr_logunif() %>%
  data.frame() 

clr_const_b2_base <- res_b2 %>%  
  data.frame() %>%
  Tjazi::clr_c() %>% 
  data.frame() 

clr_unif_b2_base <- res_b2 %>%
  data.frame() %>%
  Tjazi::clr_unif() %>%
  data.frame() 

clr_shrunk_b2_base <- res_b2 %>%
  data.frame() %>%
  sCLR() %>% 
  data.frame()

clr_new_b2_base <- res_b2 %>% 
  data.frame() %>%
  getTableMeans() %>% 
  data.frame() 

clr_logunif_b3_base <- res_b3 %>%
  data.frame() %>%
  Tjazi::clr_logunif()  %>%
  data.frame() 

clr_const_b3_base <- res_b3 %>%  
  data.frame() %>%
  Tjazi::clr_c()  %>% 
  data.frame() 

clr_unif_b3_base <- res_b3 %>%
  data.frame() %>%
  Tjazi::clr_unif() %>%
  data.frame() 

clr_shrunk_b3_base <- res_b3 %>%
  data.frame() %>%
  sCLR() %>% 
  data.frame() 

clr_new_b3_base <- res_b3 %>% 
  data.frame() %>%
  getTableMeans()  %>% 
  data.frame()

```

```{r prep individual feature precision, fig.width = 8, fig.height = 15, cache=TRUE}
clr_logunif_b1 <- clr_logunif_b1_base %>%
  mutate(real_abundance = b1) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>%
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100),
         source = "b1",
         method = "log-uniform replacement")


clr_const_b1 <- clr_const_b1_base %>%
  mutate(real_abundance = b1) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>% 
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100), 
         source = "b1", 
         method = "constant replacement") 
  

clr_unif_b1 <- clr_unif_b1_base %>%
  mutate(real_abundance = b1) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>%
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100),
         source = "b1",
         method = "uniform replacement")

clr_shrunk_b1 <- clr_shrunk_b1_base %>%
  mutate(real_abundance = b1) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>% 
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100), 
         source = "b1", 
         method = "arithmetic shrinkage") 

clr_new_b1 <- clr_new_b1_base %>%
  mutate(real_abundance = b1) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>% 
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100), 
         source = "b1", 
         method = "parameterization") 

clr_logunif_b2 <- clr_logunif_b2_base %>%
  mutate(real_abundance = b2) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>%
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100),
         source = "b2",
         method = "log-uniform replacement")

clr_const_b2 <-clr_const_b2_base %>%
  mutate(real_abundance = b2) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>% 
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100), 
         source = "b2", 
         method = "constant replacement") 

clr_unif_b2 <- clr_unif_b2_base %>%
  mutate(real_abundance = b2) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>%
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100),
         source = "b2",
         method = "uniform replacement")

clr_shrunk_b2 <- clr_shrunk_b2_base %>%
  mutate(real_abundance = b2) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>% 
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100), 
         source = "b2", 
         method = "arithmetic shrinkage") 

clr_new_b2 <- clr_new_b2_base %>%
  mutate(real_abundance = b2) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>% 
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100), 
         source = "b2", 
         method = "parameterization") 

clr_logunif_b3 <- clr_logunif_b3_base %>%
  mutate(real_abundance = b3) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>%
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100),
         source = "b3",
         method = "log-uniform replacement")


clr_const_b3 <- clr_const_b3_base %>%
  mutate(real_abundance = b3) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>% 
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100), 
         source = "b3", 
         method = "constant replacement") 

clr_unif_b3 <- clr_unif_b3_base %>%
  mutate(real_abundance = b3) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>%
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100),
         source = "b3",
         method = "uniform replacement")

clr_shrunk_b3 <- clr_shrunk_b3_base %>%
  mutate(real_abundance = b3) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>% 
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100), 
         source = "b3", 
         method = "arithmetic shrinkage") 

clr_new_b3 <- clr_new_b3_base %>%
  mutate(real_abundance = b3) %>%
  rownames_to_column("ID") %>%
  pivot_longer(!c(ID, real_abundance))  %>% 
  mutate(depth = rep(rep(seq(from = 1000, to = 20000, by = 1000), each = 100), 100), 
         source = "b3", 
         method = "parameterization") 

```

```{r plot individual feature precision, fig.width = 8, fig.height = 15}

do.call(rbind, list(
  clr_const_b1,   clr_const_b2,   clr_const_b3, 
  clr_shrunk_b1,  clr_shrunk_b2,  clr_shrunk_b3, 
  clr_new_b1,     clr_new_b2,     clr_new_b3, 
  clr_unif_b1,    clr_unif_b2,    clr_unif_b3, 
  clr_logunif_b1, clr_logunif_b2, clr_logunif_b3
                    )) %>% 
  mutate(source = str_replace(source, pattern = "b1", replacement = "10% Rare Features"), 
         source = str_replace(source, pattern = "b2", replacement = "30% Rare Features"), 
         source = str_replace(source, pattern = "b3", replacement = "50% Rare Features")) %>%
  mutate(real_abundance = as.character(real_abundance)) %>%
  mutate(real_abundance = str_replace(real_abundance, pattern = "250|350|450", replacement = "High" )) %>%

  mutate(real_abundance = factor(real_abundance, levels = c("1", "5", "15", "40", "80", "100", "High"))) %>%
  #filter(as.numeric(real_abundance) < 20) %>%
  ggplot() +
  aes(x = depth, y = value, colour = real_abundance) +
  geom_point(alpha = 1/100) + 
  geom_smooth(se = F) +
  scale_colour_manual(values = c(
    "1" = "#e41a1c", 
    "5" = "#377eb8", 
    "15" = "#4daf4a", 
    "40" = "#984ea3", 
    "80" = "#ff7f00", 
    "100" = "#ffff33", 
    "High" = "#a65628"), 
    "Sampling abundance") +
  guides(colour = guide_legend(override.aes = list(alpha = 1) ) ) +
  facet_grid(method~source, switch = "y") +
  
  theme_bw() +
  theme(legend.position = 'bottom') 

```

```{r variance by feature, fig.width = 8, fig.height = 15}
do.call(rbind, list(
  clr_const_b1,   clr_const_b2,   clr_const_b3, 
  clr_shrunk_b1,  clr_shrunk_b2,  clr_shrunk_b3, 
  clr_new_b1,     clr_new_b2,     clr_new_b3, 
  clr_unif_b1,    clr_unif_b2,    clr_unif_b3, 
  clr_logunif_b1, clr_logunif_b2, clr_logunif_b3
                    )) %>% 
  mutate(source = str_replace(source, pattern = "b1", replacement = "10% Rare Features"), 
         source = str_replace(source, pattern = "b2", replacement = "30% Rare Features"), 
         source = str_replace(source, pattern = "b3", replacement = "50% Rare Features")) %>%
  mutate(real_abundance = as.character(real_abundance)) %>%
  mutate(real_abundance = str_replace(real_abundance, pattern = "250|350|450", replacement = "High" )) %>%

  group_by(source, depth, method, real_abundance) %>%
  summarise(Variance = var(value)) %>%
  ungroup() %>%
  mutate(real_abundance = factor(real_abundance, levels = c("1", "5", "15", "40", "80", "100", "High"))) %>%
  #filter(as.numeric(real_abundance) < 20) %>%
  ggplot() +
  aes(x = depth, y = Variance, colour = real_abundance, fill = real_abundance) +
  geom_smooth(method = "loess", se = F) +
  geom_point(shape = 21, colour = "black") + 
  scale_colour_manual(values = c("1" = "#e41a1c", "5" = "#377eb8", "15" = "#4daf4a", "40" = "#984ea3", "80" = "#ff7f00", "100" = "#ffff33", "High" = "#a65628"), "Sampling abundance") +
    scale_fill_manual(values = c("1" = "#e41a1c", "5" = "#377eb8", "15" = "#4daf4a", "40" = "#984ea3", "80" = "#ff7f00", "100" = "#ffff33", "High" = "#a65628"), "Sampling abundance") +
  guides(colour = guide_legend(override.aes = list(alpha = 1) ) ) +
  facet_grid(method~source, switch = "y") +
  
  theme_bw() +
  theme(legend.position = 'bottom') 

```

```{r prep permanovas, fig.width = 8, fig.height = 5, cache=TRUE}
dist_logunif_b1 <- clr_logunif_b1_base %>%
  t() %>%
  dist(x = ., method = "euclidean")

dist_const_b1 <- clr_const_b1_base %>%
  t() %>%
  dist(x = ., method = "euclidean")  

dist_unif_b1 <- clr_unif_b1_base %>%
  t() %>%
  dist(x = ., method = "euclidean")

dist_shrunk_b1 <- clr_shrunk_b1_base %>%
  t() %>%
  dist(x = .,method = "euclidean")

dist_new_b1 <- clr_new_b1_base %>%
  t() %>%
  dist(x = ., method = "euclidean")

dist_logunif_b2 <- clr_logunif_b2_base %>%
  t() %>%
  dist(x = ., method = "euclidean")

dist_const_b2 <- clr_const_b2_base %>%
  t() %>%
  dist(x = ., method = "euclidean")  

dist_unif_b2 <- clr_unif_b2_base %>%
  t() %>%
  dist(x = ., method = "euclidean")

dist_shrunk_b2 <- clr_shrunk_b2_base %>%
  t() %>%
  dist(x = .,method = "euclidean")

dist_new_b2 <- clr_new_b2_base %>%
  t() %>%
  dist(x = ., method = "euclidean")

dist_logunif_b3 <- clr_logunif_b3_base %>%
  t() %>%
  dist(x = ., method = "euclidean")

dist_const_b3 <- clr_const_b3_base %>%
  t() %>%
  dist(x = ., method = "euclidean")  

dist_unif_b3 <- clr_unif_b3_base %>%
  t() %>%
  dist(x = ., method = "euclidean")

dist_shrunk_b3 <- clr_shrunk_b3_base %>%
  t() %>%
  dist(x = .,method = "euclidean")

dist_new_b3 <- clr_new_b3_base %>%
  t() %>%
  dist(x = ., method = "euclidean")

groups = rep(seq(1000,20000, by = 1000), each = 100)

b1_v1 <- vegan::adonis2(dist_const_b1   ~ groups, method = "euclidean", permutations = 1000)
b1_v2 <- vegan::adonis2(dist_unif_b1    ~ groups, method = "euclidean", permutations = 1000)
b1_v3 <- vegan::adonis2(dist_logunif_b1 ~ groups, method = "euclidean", permutations = 1000)
b1_v4 <- vegan::adonis2(dist_new_b1     ~ groups, method = "euclidean", permutations = 1000)
b1_v5 <- vegan::adonis2(dist_shrunk_b1  ~ groups, method = "euclidean", permutations = 1000)

adonis_b1 <- data.frame(R2 =     c(b1_v1$R2[1], 
                                   b1_v2$R2[1], 
                                   b1_v3$R2[1], 
                                   b1_v4$R2[1], 
                                   b1_v5$R2[1]), 
                        method = factor(c("constant replacement", 
                                          "uniform replacement", 
                                          "log-uniform replacement", 
                                          "parameterization", 
                                          "arithmetic shrinkage"), 
                                        levels = rev(c("constant replacement", 
                                                       "uniform replacement", 
                                                       "log-uniform replacement", 
                                                       "parameterization", 
                                                       "arithmetic shrinkage"))), 
                        distribution = "10%")


b2_v1 <- vegan::adonis2(dist_const_b2   ~ groups, method = "euclidean", permutations = 1000)
b2_v2 <- vegan::adonis2(dist_unif_b2    ~ groups, method = "euclidean", permutations = 1000)
b2_v3 <- vegan::adonis2(dist_logunif_b2 ~ groups, method = "euclidean", permutations = 1000)
b2_v4 <- vegan::adonis2(dist_new_b2     ~ groups, method = "euclidean", permutations = 1000)
b2_v5 <- vegan::adonis2(dist_shrunk_b2  ~ groups, method = "euclidean", permutations = 1000)

adonis_b2 <- data.frame(R2 =     c(b2_v1$R2[1], 
                                   b2_v2$R2[1], 
                                   b2_v3$R2[1], 
                                   b2_v4$R2[1], 
                                   b2_v5$R2[1]), 
                        method = factor(c("constant replacement", 
                                          "uniform replacement", 
                                          "log-uniform replacement", 
                                          "parameterization", 
                                          "arithmetic shrinkage"), 
                                        levels = rev(c("constant replacement", 
                                                       "uniform replacement", 
                                                       "log-uniform replacement", 
                                                       "parameterization", 
                                                       "arithmetic shrinkage"))), 
                        distribution = "30%")


b3_v1 <- vegan::adonis2(dist_const_b3   ~ groups, method = "euclidean", permutations = 1000)
b3_v2 <- vegan::adonis2(dist_unif_b3    ~ groups, method = "euclidean", permutations = 1000)
b3_v3 <- vegan::adonis2(dist_logunif_b3 ~ groups, method = "euclidean", permutations = 1000)
b3_v4 <- vegan::adonis2(dist_new_b3     ~ groups, method = "euclidean", permutations = 1000)
b3_v5 <- vegan::adonis2(dist_shrunk_b3  ~ groups, method = "euclidean", permutations = 1000)

adonis_b3 <- data.frame(R2 =     c(b3_v1$R2[1], 
                                   b3_v2$R2[1], 
                                   b3_v3$R2[1], 
                                   b3_v4$R2[1], 
                                   b3_v5$R2[1]), 
                        method = factor(c("constant replacement", 
                                          "uniform replacement", 
                                          "log-uniform replacement", 
                                          "parameterization", 
                                          "arithmetic shrinkage"), 
                                        levels = rev(c("constant replacement", 
                                                       "uniform replacement", 
                                                       "log-uniform replacement", 
                                                       "parameterization", 
                                                       "arithmetic shrinkage"))), 
                        distribution = "50%")

```

```{r prep PCAs, fig.width = 8, fig.height = 5, cache=TRUE}
const_b1.pca = clr_const_b1_base %>%
  cbind("real" = deleuze:::clr(data.frame(b1))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(const_b1.pca$sdev[1]^2/sum(const_b1.pca$sdev^2),4) * 100
pc2 <- round(const_b1.pca$sdev[2]^2/sum(const_b1.pca$sdev^2),4) * 100
pc3 <- round(const_b1.pca$sdev[3]^2/sum(const_b1.pca$sdev^2),4) * 100
pc4 <- round(const_b1.pca$sdev[4]^2/sum(const_b1.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = const_b1.pca$x[,1], 
                  PC2 = const_b1.pca$x[,2], 
                  PC3 = const_b1.pca$x[,3], 
                  PC4 = const_b1.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))

const_b1 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
  ggtitle("Constant replacement", subtitle = "10% Rare features") + 
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
  
  
new_b1.pca = clr_new_b1_base %>%
  cbind("real" = deleuze:::clr(data.frame(b1))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(new_b1.pca$sdev[1]^2/sum(new_b1.pca$sdev^2),4) * 100
pc2 <- round(new_b1.pca$sdev[2]^2/sum(new_b1.pca$sdev^2),4) * 100
pc3 <- round(new_b1.pca$sdev[3]^2/sum(new_b1.pca$sdev^2),4) * 100
pc4 <- round(new_b1.pca$sdev[4]^2/sum(new_b1.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = new_b1.pca$x[,1], 
                  PC2 = new_b1.pca$x[,2], 
                  PC3 = new_b1.pca$x[,3], 
                  PC4 = new_b1.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


new_b1 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
  ggtitle("Parametrization", subtitle = "10% Rare features") + 
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
  
  
  
  
shrunk_b1.pca = clr_shrunk_b1_base %>%
  cbind("real" = deleuze:::clr(data.frame(b1))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(shrunk_b1.pca$sdev[1]^2/sum(shrunk_b1.pca$sdev^2),4) * 100
pc2 <- round(shrunk_b1.pca$sdev[2]^2/sum(shrunk_b1.pca$sdev^2),4) * 100
pc3 <- round(shrunk_b1.pca$sdev[3]^2/sum(shrunk_b1.pca$sdev^2),4) * 100
pc4 <- round(shrunk_b1.pca$sdev[4]^2/sum(shrunk_b1.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = shrunk_b1.pca$x[,1], 
                  PC2 = shrunk_b1.pca$x[,2], 
                  PC3 = shrunk_b1.pca$x[,3], 
                  PC4 = shrunk_b1.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


shrunk_b1 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
  ggtitle("Arithmetic shrinkage", subtitle = "10% Rare features") + 
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
  
  
  
unif_b1.pca = clr_unif_b1_base %>%
  cbind("real" = deleuze:::clr(data.frame(b1))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(unif_b1.pca$sdev[1]^2/sum(unif_b1.pca$sdev^2),4) * 100
pc2 <- round(unif_b1.pca$sdev[2]^2/sum(unif_b1.pca$sdev^2),4) * 100
pc3 <- round(unif_b1.pca$sdev[3]^2/sum(unif_b1.pca$sdev^2),4) * 100
pc4 <- round(unif_b1.pca$sdev[4]^2/sum(unif_b1.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = unif_b1.pca$x[,1], 
                  PC2 = unif_b1.pca$x[,2], 
                  PC3 = unif_b1.pca$x[,3], 
                  PC4 = unif_b1.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


unif_b1 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
  ggtitle("Uniform replacement", subtitle = "10% Rare features") + 
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
  
  
  logunif_b1.pca = clr_logunif_b1_base %>%
  cbind("real" = deleuze:::clr(data.frame(b1))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(logunif_b1.pca$sdev[1]^2/sum(logunif_b1.pca$sdev^2),4) * 100
pc2 <- round(logunif_b1.pca$sdev[2]^2/sum(logunif_b1.pca$sdev^2),4) * 100
pc3 <- round(logunif_b1.pca$sdev[3]^2/sum(logunif_b1.pca$sdev^2),4) * 100
pc4 <- round(logunif_b1.pca$sdev[4]^2/sum(logunif_b1.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = logunif_b1.pca$x[,1], 
                  PC2 = logunif_b1.pca$x[,2], 
                  PC3 = logunif_b1.pca$x[,3], 
                  PC4 = logunif_b1.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


logunif_b1 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
  ggtitle("Log-uniform replacement", subtitle = "10% Rare features") + 
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
    
  
const_b2.pca = clr_const_b2_base %>%
  cbind("real" = deleuze:::clr(data.frame(b2))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(const_b2.pca$sdev[1]^2/sum(const_b2.pca$sdev^2),4) * 100
pc2 <- round(const_b2.pca$sdev[2]^2/sum(const_b2.pca$sdev^2),4) * 100
pc3 <- round(const_b2.pca$sdev[3]^2/sum(const_b2.pca$sdev^2),4) * 100
pc4 <- round(const_b2.pca$sdev[4]^2/sum(const_b2.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = const_b2.pca$x[,1] * -1, 
                  PC2 = const_b2.pca$x[,2], 
                  PC3 = const_b2.pca$x[,3], 
                  PC4 = const_b2.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


const_b2 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
  #ggtitle("constant replacement") + 
  ggtitle("", subtitle = "30% Rare features") +
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
  
  
new_b2.pca = clr_new_b2_base %>%
  cbind("real" = deleuze:::clr(data.frame(b2))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(new_b2.pca$sdev[1]^2/sum(new_b2.pca$sdev^2),4) * 100
pc2 <- round(new_b2.pca$sdev[2]^2/sum(new_b2.pca$sdev^2),4) * 100
pc3 <- round(new_b2.pca$sdev[3]^2/sum(new_b2.pca$sdev^2),4) * 100
pc4 <- round(new_b2.pca$sdev[4]^2/sum(new_b2.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = new_b2.pca$x[,1], 
                  PC2 = new_b2.pca$x[,2], 
                  PC3 = new_b2.pca$x[,3], 
                  PC4 = new_b2.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


new_b2 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
  #ggtitle("constant replacement") + 
  ggtitle("", subtitle = "30% Rare features") +
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
  
  
  
  
shrunk_b2.pca = clr_shrunk_b2_base %>%
  cbind("real" = deleuze:::clr(data.frame(b2))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(shrunk_b2.pca$sdev[1]^2/sum(shrunk_b2.pca$sdev^2),4) * 100
pc2 <- round(shrunk_b2.pca$sdev[2]^2/sum(shrunk_b2.pca$sdev^2),4) * 100
pc3 <- round(shrunk_b2.pca$sdev[3]^2/sum(shrunk_b2.pca$sdev^2),4) * 100
pc4 <- round(shrunk_b2.pca$sdev[4]^2/sum(shrunk_b2.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = shrunk_b2.pca$x[,1], 
                  PC2 = shrunk_b2.pca$x[,2], 
                  PC3 = shrunk_b2.pca$x[,3], 
                  PC4 = shrunk_b2.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


shrunk_b2 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
    #ggtitle("constant replacement") + 
  ggtitle("", subtitle = "30% Rare features") +
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
  
  
  
unif_b2.pca = clr_unif_b2_base %>%
  cbind("real" = deleuze:::clr(data.frame(b2))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(unif_b2.pca$sdev[1]^2/sum(unif_b2.pca$sdev^2),4) * 100
pc2 <- round(unif_b2.pca$sdev[2]^2/sum(unif_b2.pca$sdev^2),4) * 100
pc3 <- round(unif_b2.pca$sdev[3]^2/sum(unif_b2.pca$sdev^2),4) * 100
pc4 <- round(unif_b2.pca$sdev[4]^2/sum(unif_b2.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = unif_b2.pca$x[,1] * -1, 
                  PC2 = unif_b2.pca$x[,2], 
                  PC3 = unif_b2.pca$x[,3], 
                  PC4 = unif_b2.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


unif_b2 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels  
  #ggtitle("constant replacement") + 
  ggtitle("", subtitle = "30% Rare features") +
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
  
  
  logunif_b2.pca = clr_logunif_b2_base %>%
  cbind("real" = deleuze:::clr(data.frame(b2))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(logunif_b2.pca$sdev[1]^2/sum(logunif_b2.pca$sdev^2),4) * 100
pc2 <- round(logunif_b2.pca$sdev[2]^2/sum(logunif_b2.pca$sdev^2),4) * 100
pc3 <- round(logunif_b2.pca$sdev[3]^2/sum(logunif_b2.pca$sdev^2),4) * 100
pc4 <- round(logunif_b2.pca$sdev[4]^2/sum(logunif_b2.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = logunif_b2.pca$x[,1], 
                  PC2 = logunif_b2.pca$x[,2], 
                  PC3 = logunif_b2.pca$x[,3], 
                  PC4 = logunif_b2.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


logunif_b2 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
    #ggtitle("constant replacement") + 
  ggtitle("", subtitle = "30% Rare features") +
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 

  
const_b3.pca = clr_const_b3_base %>%
  cbind("real" = deleuze:::clr(data.frame(b3))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(const_b3.pca$sdev[1]^2/sum(const_b3.pca$sdev^2),4) * 100
pc2 <- round(const_b3.pca$sdev[2]^2/sum(const_b3.pca$sdev^2),4) * 100
pc3 <- round(const_b3.pca$sdev[3]^2/sum(const_b3.pca$sdev^2),4) * 100
pc4 <- round(const_b3.pca$sdev[4]^2/sum(const_b3.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = const_b3.pca$x[,1] * -1, 
                  PC2 = const_b3.pca$x[,2], 
                  PC3 = const_b3.pca$x[,3], 
                  PC4 = const_b3.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


const_b3 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
    #ggtitle("constant replacement") + 
  ggtitle("", subtitle = "50% Rare features") +
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
  
  
new_b3.pca = clr_new_b3_base %>%
  cbind("real" = deleuze:::clr(data.frame(b3))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(new_b3.pca$sdev[1]^2/sum(new_b3.pca$sdev^2),4) * 100
pc2 <- round(new_b3.pca$sdev[2]^2/sum(new_b3.pca$sdev^2),4) * 100
pc3 <- round(new_b3.pca$sdev[3]^2/sum(new_b3.pca$sdev^2),4) * 100
pc4 <- round(new_b3.pca$sdev[4]^2/sum(new_b3.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = new_b3.pca$x[,1], 
                  PC2 = new_b3.pca$x[,2], 
                  PC3 = new_b3.pca$x[,3], 
                  PC4 = new_b3.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


new_b3 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
  #ggtitle("parametrization") + 
  ggtitle("", subtitle = "50% Rare features") +
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
  
  
  
  
shrunk_b3.pca = clr_shrunk_b3_base %>%
  cbind("real" = deleuze:::clr(data.frame(b3))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(shrunk_b3.pca$sdev[1]^2/sum(shrunk_b3.pca$sdev^2),4) * 100
pc2 <- round(shrunk_b3.pca$sdev[2]^2/sum(shrunk_b3.pca$sdev^2),4) * 100
pc3 <- round(shrunk_b3.pca$sdev[3]^2/sum(shrunk_b3.pca$sdev^2),4) * 100
pc4 <- round(shrunk_b3.pca$sdev[4]^2/sum(shrunk_b3.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = shrunk_b3.pca$x[,1], 
                  PC2 = shrunk_b3.pca$x[,2], 
                  PC3 = shrunk_b3.pca$x[,3], 
                  PC4 = shrunk_b3.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


shrunk_b3 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
  #ggtitle("parametrization") + 
  ggtitle("", subtitle = "50% Rare features") +
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
  
  
  
unif_b3.pca = clr_unif_b3_base %>%
  cbind("real" = deleuze:::clr(data.frame(b3))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(unif_b3.pca$sdev[1]^2/sum(unif_b3.pca$sdev^2),4) * 100
pc2 <- round(unif_b3.pca$sdev[2]^2/sum(unif_b3.pca$sdev^2),4) * 100
pc3 <- round(unif_b3.pca$sdev[3]^2/sum(unif_b3.pca$sdev^2),4) * 100
pc4 <- round(unif_b3.pca$sdev[4]^2/sum(unif_b3.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = unif_b3.pca$x[,1], 
                  PC2 = unif_b3.pca$x[,2], 
                  PC3 = unif_b3.pca$x[,3], 
                  PC4 = unif_b3.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


unif_b3 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
  #ggtitle("parametrization") + 
  ggtitle("", subtitle = "50% Rare features") +
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
  
  
  logunif_b3.pca = clr_logunif_b3_base %>%
  cbind("real" = deleuze:::clr(data.frame(b3))[,1]) %>%
  t() %>%
  prcomp()

#Extract the amount of variance the first four components explain for plotting. 
pc1 <- round(logunif_b3.pca$sdev[1]^2/sum(logunif_b3.pca$sdev^2),4) * 100
pc2 <- round(logunif_b3.pca$sdev[2]^2/sum(logunif_b3.pca$sdev^2),4) * 100
pc3 <- round(logunif_b3.pca$sdev[3]^2/sum(logunif_b3.pca$sdev^2),4) * 100
pc4 <- round(logunif_b3.pca$sdev[4]^2/sum(logunif_b3.pca$sdev^2),4) * 100

#Extract the scores for every sample for the first four components for plotting. 
pca  = data.frame(PC1 = logunif_b3.pca$x[,1], 
                  PC2 = logunif_b3.pca$x[,2], 
                  PC3 = logunif_b3.pca$x[,3], 
                  PC4 = logunif_b3.pca$x[,4])

pca$samples = factor(x = c(rep(seq(1000,20000, by = 1000), each = 100), "real"), 
                     levels = unique(c(seq(1000,20000, by = 1000), "real")))


logunif_b3 = ggplot(pca) +  
  
  aes(x = PC1, y = PC2, fill = samples) +
  
  #Create the points and ellipses
  stat_ellipse(geom = "polygon", alpha = 1/4) +
  geom_point(col = "black", shape = 21, 
             aes(size = samples == "real")) + 
  #Adjust appearance
  
  #Adjust labels
  #ggtitle("parametrization") + 
  ggtitle("", subtitle = "50% Rare features") +
  xlab(paste("PC1: ", pc1,  "%", sep="")) + 
  ylab(paste("PC2: ", pc2,  "%", sep="")) +
  theme_bw() +
  theme(legend.position = 'bottom') 
```

```{r plot PCAs, fig.width = 8, fig.height = 15}
  
  ((const_b1   | const_b2   | const_b3)   )/
  ((unif_b1    | unif_b2    | unif_b3)    )/
  ((logunif_b1 | logunif_b2 | logunif_b3) )/
  ((new_b1     | new_b2     | new_b3)     )/
  ((shrunk_b1  | shrunk_b2  | shrunk_b3)  ) +
  patchwork::plot_layout(guides = 'collect')  & theme(legend.position = 'bottom')
    
        
```


```{r plot permanovas, fig.width = 8, fig.height = 5}


do.call(rbind, list(adonis_b1, adonis_b2, adonis_b3)) %>%
  mutate(distribution = factor(distribution, levels = rev(c("10%", "30%", "50%")))) %>%

ggplot() +
  
  aes(x = R2, y = method, fill = distribution, colour = distribution, groups = distribution) + 
  
  geom_bar(stat = "identity", position = position_dodge(0.5), width = 1/5)+
  geom_point(size = 4, shape = 21, colour = "black", position = position_dodge2(0.5, preserve = "total")) +
  #facet_wrap(~distribution) +
  
  theme_bw() +
  theme(legend.position = 'bottom') + 
  scale_x_continuous(limits = c(0,.1)) +
  scale_fill_manual(values = c("10%" = "#feb24c", "30%" = "#fc4e2a", "50%" = "#800026"), "Rare features",
                      guide = guide_legend(reverse = TRUE)) +
  scale_colour_manual(values = c("10%" = "#feb24c", "30%" = "#fc4e2a", "50%" = "#800026"), "Rare features",
                      guide = guide_legend(reverse = TRUE))+

  ylab("") + 
  xlab(Variance~explained~by~sampling~depth~(R^2)) +
  ggtitle("The effect of sampling depth is dependent on zero imputation strategy")

```
