# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pw_dist_cpp <- function(x) {
    .Call('_deleuze_pw_dist_cpp', PACKAGE = 'deleuze', x)
}

